services:
  - type: web
    name: event-monolith-app
    env: node
    plan: free
    buildCommand: |
      npm install
      npx prisma generate
      npx prisma db push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_JyLlS6H2hRnd@ep-billowing-wildflower-a42jg3eb-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: ETHEREAL_USER
        value: bxuydshbtaalihcd@ethereal.email
      - key: ETHEREAL_PASS
        value: DzEqS3badWYsCnzSyM
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000